### ISSUE TITLE
two question maybe an issue

### ISSUE THREAD

**Issue by StephanElter** [JingShing/Python-Bayer-Dithering#1]
Hey JingShing
nice job providing this. :)
i have prob two findings:
1.  if color >= (color>>2) > matrix[row&matrix_len][col&matrix_len]:
do you really need the first condition? the first condition is always fullfilled
2. i guess the indexing formula e.g. row&matrix_len does only work for 8,4 and 2 but not for 3 or isnt it?
in case of 3 you get only index of 0 or 2 but never 1. i guess you want do somthing like modulo or?
regards Stephan

**Comment by JingShing** [comment]
Sorry for your problems. That these codes are my old codes so it may be silly or broke.

first question. That I was experimenting some feature so some condition or part may look useless.

Seconed question. Ya I just do the modulo or but maybe in that time I just don't know this operator.

Sorry for your problems. This repo is for my note or experiment code. And it is my old codes. Thanks for your issue.
